### ISSUE TITLE
Remote server can’t use

### ISSUE THREAD

**Issue by kkishnani** [RasPlex/RasPlex#648] opened 2021-10-03 09:38 UTC
Remote server on rasplex was working fine until it stopped for some reason… 
It works on iOS devices nicely just doesn’t work on rasplex. 
Plex server website also says connected with outside network. 

**RPi model**: [3B+]
**RasPlex**: [1.8.0 default skin]
**PMS**: [1.24.3.5033 and synology dsm7.0]
**Network**: [ethernet]

**Comment by nightmare04** [comment] 2021-10-03 11:16
Yes, remote server not work with rasplex client

**Comment by kkishnani** [comment] 2021-10-03 11:46
> Yes, remote server not work with rasplex client

But It did work for couple of days at first.

**Comment by nightmare04** [comment] 2021-10-03 11:54
> > Yes, remote server not work with rasplex client
> 
> But It did work for couple of days at first.

Yes

**Comment by kkishnani** [comment] 2021-10-03 12:03
> > > Yes, remote server not work with rasplex client
> > 
> > 
> > But It did work for couple of days at first.
> 
> Yes

So what do you mean? It works for first few days and then it stops? I don’t think so it should either work or it should not…

**Comment by nightmare04** [comment] 2021-10-03 12:08
It works many years, and stop work yesterday 1 October

**Comment by dalehamel** [comment] 2021-10-03 12:46
This is a duplicate of https://github.com/RasPlex/RasPlex/issues/645

The problem is that on Sept 30, the root CA certificate that LetsEncrypt service uses (which Plex Inc uses) expired. There is a bug in the old version of OpenSSL that Rasplex uses where if this expired root CA exists, it fails to fallback to the new root CA, even though it has it.

We fixed this issue by repackaging the images to update the CA certificates https://github.com/RasPlex/RasPlex/releases/tag/1.8.0b

Update rasplex by either re-flashing the image, or copying the SYSTEM and SYSTEM.md5 file to your SD card.

**Closed as completed by dalehamel** 2021-10-03 12:46 UTC
