### ISSUE TITLE
audio is not released when not producing sound

### ISSUE THREAD

**Issue by xortim** [RasPlex/RasPlex#357] opened 2015-02-24 20:25 UTC
Pi Model: B v2
Serial: 000000001a63b942
rasplex Version: 0.5.1
rasplex git: 55113f6ddae290c431fdf96171c28c1778fbe1ff
Type of SD card: class 10
Internet connection type: Ethernet 
Installed via dd of img file from Linux

Not sure if this is a bug with PHT or one of the supporting libraries or the new Pi2 hardware.
 
My Denon 2308CI AVR allows me to tell an input to auto-select the audio source. My use case for this is a TOSLink from my TV for the built in apps which cannot run on RasPlex (YouTube, etc.) and HDMI for RasPlex. Prior to the Pi2 and 0.5.1 if I stopped all playback on RasPlex and launched the Netflix app on my TV, my AVR would auto-select the audio source which was providing the audio. So I didn't have to change inputs/audio source, just make sure only one audio source was producing sound at once. Very, very simple.
 
After the upgrade (pi2 with 0.5.1), this no longer works. I have to manually tell the AVR to use the TOSLink ("Digital") or HDMI as the audio source by hand. At a high level my guess is that RasPlex has started sending silence over HDMI instead of nothing. On 0.5.0 this behavior can be duplicated by starting something with audio (movie, music) and hitting pause instead of stop. Pause = sending silence, Stop = not sending any audio.
 
I plan on running through some trial and error to narrow it down to 0.5.1 or hardware difference with Pi vs Pi2. Any tracing or logs I should enable to help capture relevant info?
 
I understand this isn't a common use case and I'm probably taking advantage of some unexpected behavior - but it's an undocumented functionality change that I noticed.

Could this also be blocking CEC functionality? (related: https://github.com/RasPlex/RasPlex/issues/331)

**Comment by dalehamel** [comment] 2015-02-24 20:30
This definitely seems like something CEC related or something to do with the HDMI protocol. I use an amp but it provides both the video and audio stream together. It could be that the signal isn't properly being relayed to the cec driver, or that there is a mismatch between libcec and the kernel being used.

I use an amp, and it passes the video and audio signal together so there's no issue.

The biggest change between 0.5.0 and 0.5.1 was the kernel upgrade, so it's quite likely this could be the device handling. Could you try on an RPi1 with 0.5.1?

We're currently developing 0.6.0 which will upgrade both the kernel AND the underlying OS, which includes an update to libcec. I wonder if this will fix your problem? None of the logic in the plex app for dealing with CEC changed from 0.5.0 to 0.5.1, in fact, they are actually running pretty much the exact same code aside from detecting in a small number of codepaths if it's RPi1 or RPi2, it was almost entirely a kernel and firmware upgrade.

**Comment by xortim** [comment] 2015-02-24 21:58
I confirmed the same behavior in 0.5.1 on the original 512mb Model B.

**Comment by yannlet** [comment] 2015-02-28 07:53
Thank you Xortim ..... I have exactly the same issue ... but didn't know how to describe it :-)
I have a Yamaha amplifier, and since 5.1 the source can't autoswitch anymore. It is exactly as you said, some kind of "silence over HDMI" instead of nothing, preventing to automatically switch to another source.
I have a RP1, and it makes this version unusable, I had to revert to 5.0

**Comment by xortim** [comment] 2015-04-27 23:30
This is still present in the 0.6 release.

**Comment by yannlet** [comment] 2015-05-17 14:11
Yes, same here with 0.6 and RPi 2

**Comment by NedtheNerd** [comment] 2015-05-21 10:11
Have you checked that 'Send "inactive source" command when stopping XBMC' in Preferences->System->Input Devices->Peripherals->CEC Adapter is enabled?

**Comment by xortim** [comment] 2015-05-21 10:41
Yup. That's a default value, haven't changed that. I think it also only applies when the Pi goes into standby

**Comment by xortim** [comment] 2015-06-03 18:57
I've been doing some research (and by that I mean discussing this with people smarter than me):

TOSLink protocol negotiation takes about half a second and each time a protocol change occurred, a link renegotiation would occur. At best, you'll hear an interruption in audio each time the link is renegotiatied
at worst, you get a pop or about a half second delay in starting the audio, at worst the receiver will miss the negotiation and produce static. To make this transparent to the user, the highest possible audio stream is selected at all times, and upsampling is done in the device; silence is played so the link never goes dead during the absence of audio so renegotiation in the link doesn't occur.

I highly doubt that this is a CEC issue and more likely it's a broadcom firmware or kernel driver issue.

Do we have the exact versions of all of the above between the kernels, firmware and libCEC from 0.5.0 and 0.5.1?

**Comment by NedtheNerd** [comment] 2015-07-19 15:57
Can you please check this issue in the latest release 0.7.0 (released today) and advise.

**Comment by xortim** [comment] 2015-07-20 11:46
Confirmed that the issue is present in 0.7.0.

**Comment by yannlet** [comment] 2015-07-22 14:04
I confirm that the issue is present. I found a workaround by selecting numeric instead of HDMI for the output (same results for the sound but audio is released).

**Comment by xortim** [comment] 2015-07-22 22:47
I can confirm the workaround for this. Thanks, @yannlet!

My settings are
Audio output: **HDMI**
Audio offset: 0ms
Dolby Digital (AC3) capable receiver: on
Dolby Digital Plug (E-AC3) capable receiver: on
DTS capable receiver: on
Output sereo to all speakers: off
Boost volume level on downmix: on
Audio output channels: **5.1**
Audio output device: **Analogue**
Passthrough output device: **HDMI**
Play GUI sounds: Always

Changing the value of "Audio output device" to anything other than "Analogue" results in the issue described in my original post.

Maybe a patch to PHT to adjust the verbiage for this to indicate the behavior is in order?

**Comment by xortim** [comment] 2015-07-24 03:09
After further testing. This workaround - like all workarounds - doesn't really work. 

It only addressed the symptoms of the problem when the audio encoding is included in the "passthrough" formats: AC3, DTS, etc. All others are output to the analog device, resulting in no sound.

**Comment by xortim** [comment] 2015-09-08 15:08
I was messing around with Kodi + Emby on my RPi and noticed that Kodi has an Audio setting for "Keep audio device alive" that described this behavior exactly. Was this setting stripped from PHT or RasPlex intentionally?

http://kodi.wiki/view/Audio_settings

**Comment by NedtheNerd** [comment] 2015-09-08 15:12
Can you check latest release 0.7.1 and advise.

**Comment by xortim** [comment] 2015-09-08 15:14
I just finished updated to 0.7.1 and the issue is still present. I'm thinking it's tied to that Audio setting not being configurable and set to "Always."

**Comment by xortim** [comment] 2015-09-25 12:06
@NedtheNerd - do you know if it's possible to add this setting into one of the XML files directly? I'll have to do some digging in Kodi to see what the actual configuration change is for this.

**Comment by yannlet** [comment] 2015-11-21 19:35
Issue still present in 1.0

**Comment by NedtheNerd** [comment] 2016-06-06 23:01
There is now an option to configure this in Preferences, can you please try in latest version 1.6.0 and advise.

**Comment by NedtheNerd** [comment] 2016-06-27 06:14
No further response, closing issue

**Closed by NedtheNerd** 2016-06-27 06:14 UTC
