### ISSUE TITLE
Easycap stk1160 not working anymore

### ISSUE THREAD

**Issue by posthok** [RasPlex/RasPlex#326] opened 2014-12-16 20:34 UTC
hyperion support with stk1160 would be nice.
worked fine in 0.4.0 rc4

**Comment by dalehamel** [comment] 2015-02-13 16:20
Is this still an issue in 0.5.1 @posthok?

**Comment by NedtheNerd** [comment] 2015-02-14 17:51
Duplicate of #350, closing

**Closed by NedtheNerd** 2015-02-14 17:51 UTC
