### ISSUE TITLE
Channels: Error "Couldn't retrieve the play queue for this item. Please try again"

### ISSUE THREAD

**Issue by Alatriste79** [RasPlex/RasPlex#523] opened 2016-07-22 08:12 UTC
Hi guys,

Since a few days ago I started having this error message when I try to play any content from the Channels option, in the Plex version of the Raspberry Pi 2, using the latest version of the iOS app to control it:

Error "Couldn't retrieve the play queue for this item. Please try again"

I'm using the lasted software version available for iOS and Raspberry Pi. (it got updated recently)

I'm playing the content using the Ethernet connection. The rest of the content plays without any issues. I can also play the content right into my iOS Plex app, but not in the Raspberry.

**Comment by NedtheNerd** [comment] 2016-07-22 16:31
Duplicate of #513 

Closing issue.

**Closed by NedtheNerd** 2016-07-22 16:31 UTC
